### ISSUE TITLE
Refactor DB models

### ISSUE THREAD

**Issue by heyitaki** [wormhole-foundation/wormhole-monitor#30]
The current models used in the db require chain-specific logic within the `Database` classes because different chains are storing different information within the strings. Instead, it would be nice to pass objects back and forth and have each `Database` transform them into whatever data type they store.

**Comment by heyitaki** [comment]
After discussion, we decided that we should pass around a list of messages, here is a proposal for that:

```typescript
export type WormholeMessage = {
  key: string;
  blockNumber: string;
  timestamp: string;
  transactionHash: string;
  chain: ChainName;
  emitter: string;
  sequence: string;
};
```

Where `key` is a string of format `${chainId}/${blockNumber}/${txPositionInBlock}`. `txPositionInBlock` just needs to be some property that provides sorting of messages within the same block. This enables us to sort at the tx level instead of the block level, which is useful for data retrieval as well as keeping track of the last message seen.

**Comment by ckeun** [comment]
I like this idea. More descriptive than just the current vaasByBlock.
